name: Build and Deploy demo to gh-pages
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Angular Deploy gh-pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          github_access_token: ${{ secrets.GH_TOKEN }} # see the Configuration section for how you can create secrets
          build_configuration: production # The build environment for the app. please look configurations in your angular.json
          base_href: '' # empty string to support optional base-href
          deploy_branch: gh-pages # The branch the action should deploy to.
          angular_dist_build_folder: dist/demo # The folder where your project is supposed to be after running ng build by the action.
