name: Build and Deploy demo to gh-pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Angular Deploy gh-pages Actions
      uses: samuelnygaard/angular-deploy-gh-pages-actions@master
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
        build_configuration: production # The build environment for the app. please look configurations in your angular.json
        deploy_branch: gh-pages # The branch the action should deploy to.
        build_folder: dist/demo # The folder where your project is supposed to be after running ng build by the action.
