on:
  push:
    branches:
      - master
name: Build & Release Angular
jobs:
  release:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and npm run build
        run: |
          npm i
          npm run build:prod
      - name: npm test
        run: npm run test
      - name: Publish
        uses: mikeal/merge-release@v4.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          DEPLOY_DIR: dist/ngx-timezones
